src/Entity/RegimentUsers.php
<?php

namespace App\Entity;

use App\Repository\RegimentUsersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RegimentUsersRepository::class)]
class RegimentUsers
{

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'integer', unique: true)]
    private $socId;

    #[ORM\Column(type: 'integer')]
    private $level;

    #[ORM\Column(type: 'integer')]
    private $sut;

    #[ORM\Column(type: 'integer')]
    private $used_talents;

    #[ORM\Column(type: 'integer')]
    private $login_time;

    #[ORM\Column(type: 'integer')]
    private $total_damage;

    #[ORM\Column(type: 'integer')]
    private $created;

    #[ORM\Column(type: 'object')]
    private $achievements;

    #[ORM\Column(type: 'string', length: 255)]
    private $first_name;

    #[ORM\Column(type: 'string', length: 255)]
    private $last_name;

    #[ORM\Column(type: 'string', length: 255)]
    private $photo_50;

    #[ORM\Column(type: 'integer')]
    private $updateTime;

    #[ORM\Column(type: 'integer')]
    private $experience = 0;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: RegimentStatsUsers::class, cascade: ['persist', 'remove'])]
    private $regimentStatsUsers;

    public function __construct()
    {
        $this->regimentStatsUsers = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSocId(): ?int
    {
        return $this->socId;
    }

    public function setSocId(int $socId): self
    {
        $this->socId = $socId;

        return $this;
    }

    public function getLevel(): ?int
    {
        return $this->level;
    }

    public function setLevel(int $level): self
    {
        $this->level = $level;

        return $this;
    }

    public function getSut(): ?int
    {
        return $this->sut;
    }

    public function setSut(int $sut): self
    {
        $this->sut = $sut;

        return $this;
    }

    public function getUsedTalents(): ?int
    {
        return $this->used_talents;
    }

    public function setUsedTalents(int $used_talents): self
    {
        $this->used_talents = $used_talents;

        return $this;
    }

    public function getLoginTime(): ?int
    {
        return $this->login_time;
    }

    public function setLoginTime(int $login_time): self
    {
        $this->login_time = $login_time;

        return $this;
    }

    public function getTotalDamage(): ?int
    {
        return $this->total_damage;
    }

    public function setTotalDamage(int $total_damage): self
    {
        $this->total_damage = $total_damage;

        return $this;
    }

    public function getCreated(): ?int
    {
        return $this->created;
    }

    public function setCreated(int $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getAchievements()
    {
        return $this->achievements;
    }

    public function setAchievements($achievements): self
    {
        $this->achievements = $achievements;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getPhoto50(): ?string
    {
        return $this->photo_50;
    }

    public function setPhoto50(string $photo_50): self
    {
        $this->photo_50 = $photo_50;

        return $this;
    }

    public function getUpdateTime(): ?int
    {
        return $this->updateTime;
    }

    public function setUpdateTime(int $updateTime): self
    {
        $this->updateTime = $updateTime;

        return $this;
    }

    public function getExperience(): ?int
    {
        return $this->experience;
    }

    public function setExperience(int $experience): self
    {
        $this->experience = $experience;

        return $this;
    }

    /**
     * @return Collection|RegimentStatsUsers[]
     */
    public function getRegimentStatsUsers(): Collection
    {
        return $this->regimentStatsUsers;
    }

    public function addRegimentStatsUser(RegimentStatsUsers $regimentStatsUser): self
    {
        if (!$this->regimentStatsUsers->contains($regimentStatsUser)) {
            $this->regimentStatsUsers[] = $regimentStatsUser;
            $regimentStatsUser->setUser($this);
        }

        return $this;
    }

    public function removeRegimentStatsUser(RegimentStatsUsers $regimentStatsUser): self
    {
        if ($this->regimentStatsUsers->removeElement($regimentStatsUser)) {
            // set the owning side to null (unless already changed)
            if ($regimentStatsUser->getUser() === $this) {
                $regimentStatsUser->setUser(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Integer;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string')]
    private int $vkontakteID;

    #[ORM\Column(type: 'integer')]
    private $updateTime;

    #[ORM\Column(type: 'string', length: 255)]
    private $access_token;

    #[ORM\Column(type: 'string', length: 255)]
    private $first_name;

    #[ORM\Column(type: 'string', length: 255)]
    private $last_name;

    #[ORM\Column(type: 'string', length: 255)]
    private $screen_name;

    #[ORM\Column(type: 'string', length: 255)]
    private $photo_medium;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Ads::class)]
    private $ads;

    #[ORM\OneToOne(mappedBy: 'user', targetEntity: UsersToken::class, cascade: ['persist', 'remove'])]
    private $usersToken;

    public function __construct()
    {
        $this->ads = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return int
     */
    public function getVkontakteID(): int
    {
        return $this->vkontakteID;
    }

    /**
     * @param mixed $vkontakteID
     */
    public function setVkontakteID(int $vkontakteID): self
    {
        $this->vkontakteID = $vkontakteID;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }


    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getUpdateTime(): ?int
    {
        return $this->updateTime;
    }

    public function setUpdateTime(int $updateTime): self
    {
        $this->updateTime = $updateTime;

        return $this;
    }

    public function getAccessToken(): ?string
    {
        return $this->access_token;
    }

    public function setAccessToken(string $access_token): self
    {
        $this->access_token = $access_token;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getScreenName(): ?string
    {
        return $this->screen_name;
    }

    public function setScreenName(string $screen_name): self
    {
        $this->screen_name = $screen_name;

        return $this;
    }

    public function getPhotoMedium(): ?string
    {
        return $this->photo_medium;
    }

    public function setPhotoMedium(string $photo_medium): self
    {
        $this->photo_medium = $photo_medium;

        return $this;
    }

    /**
     * @return Collection|Ads[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ads $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setUser($this);
        }

        return $this;
    }

    public function removeAd(Ads $ad): self
    {
        if ($this->ads->removeElement($ad)) {
            // set the owning side to null (unless already changed)
            if ($ad->getUser() === $this) {
                $ad->setUser(null);
            }
        }

        return $this;
    }

    public function getUsersToken(): ?UsersToken
    {
        return $this->usersToken;
    }

    public function setUsersToken(?UsersToken $usersToken): self
    {
        // unset the owning side of the relation if necessary
        if ($usersToken === null && $this->usersToken !== null) {
            $this->usersToken->setUser(null);
        }

        // set the owning side of the relation if necessary
        if ($usersToken !== null && $usersToken->getUser() !== $this) {
            $usersToken->setUser($this);
        }

        $this->usersToken = $usersToken;

        return $this;
    }
}

src/Entity/UsersScript.php
<?php

namespace App\Entity;

use App\Repository\UsersScriptRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UsersScriptRepository::class)]
class UsersScript
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'integer')]
    private $platformId;

    #[ORM\Column(type: 'integer')]
    private $created;

    #[ORM\Column(type: 'string', length: 255)]
    private $photo_50;

    #[ORM\Column(type: 'string', length: 255)]
    private $last_name;

    #[ORM\Column(type: 'string', length: 255)]
    private $first_name;

    #[ORM\Column(type: 'integer')]
    private $lastTime;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPlatformId(): ?int
    {
        return $this->platformId;
    }

    public function setPlatformId(int $platformId): self
    {
        $this->platformId = $platformId;

        return $this;
    }

    public function getCreated(): ?int
    {
        return $this->created;
    }

    public function setCreated(int $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getPhoto50(): ?string
    {
        return $this->photo_50;
    }

    public function setPhoto50(string $photo_50): self
    {
        $this->photo_50 = $photo_50;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastTime(): ?int
    {
        return $this->lastTime;
    }

    public function setLastTime(int $lastTime): self
    {
        $this->lastTime = $lastTime;

        return $this;
    }
}

src/Controller/TopController.php
<?php

namespace App\Controller;

use App\Repository\RegimentStatsUsersRepository;
use App\Repository\RegimentUsersRepository;
use App\Service\RegimentLibs;
use App\Service\Top;
use App\Service\Vkontakte;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TopController extends AbstractController
{

    #[
        Route('/calculator', name: 'top-calculator')
    ]
    public function calculator(): Response
    {
        return $this->render('top/calculator.html.twig');
    }

    #[
        Route('/top/stats/{id<\d+>}', name: 'top-stats')
    ]
    public function stats(Request $request, int $id, RegimentStatsUsersRepository $statsUsersRepository, RegimentUsersRepository $regimentUsersRepository): Response
    {
        return $this->render('top/stats.html.twig', [
            'stats' => $statsUsersRepository->findBy(['user' => $id],  ['created' => 'DESC']),
            'user' => $regimentUsersRepository->find($id)
        ]);
    }

    #[Route('/top', name: 'top')]
    public function index(Request $request, PaginatorInterface $paginator, RegimentUsersRepository $regimentUsersRepository, Top $top): Response
    {
        $friends = $top->getFriends();

        $users = $paginator->paginate($regimentUsersRepository->findLatest($request->query->get('friends', 'all'), $friends), $request->query->getInt('page', 1), 250, [
            'defaultSortDirection' => 'desc'
        ]);
        $users->setTotalItemCount(2500);


        if($this->isGranted('IS_AUTHENTICATED')){
            $profile = [
                'top' => $regimentUsersRepository->rank($this->getUser()->getVkontakteID()),
                'user' => $regimentUsersRepository->findOneBy(['socId' => $this->getUser()->getVkontakteID()])
            ];
        } else $profile = [];

        return $this->render('top/index.html.twig', [
            'pagination' => $users,
            'update' => $regimentUsersRepository->updateTime(),
            'friends' => $friends,
            'level' => RegimentLibs::LEVEL,
            'profile' => $profile
        ]);
    }
}

templates/top/calculator.html.twig
<script>

    let favorites = [];
    await this.page.goto('https://www.dream-singles.com/members/account/listMenWhoBlockedLady', {
        waitUntil: 'networkidle2',
    }).catch(async (err) => {
        //clg
        await this.page.goto('https://www.dream-singles.com/members/account/listMenWhoBlockedLady', {
            waitUntil: 'networkidle2',
        }).catch((err) => {
            /**add error to front */
            //clg
        })
    });


</script>

templates/top/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Топ игроков игры Храбрый Полк    {% endblock %}
{% block header 'Топ игроков игры Храбрый Полк' %}
{% set damage = [
    100000,
    250000,
    500000,
    1000000,
    3000000,
    5000000,
    10000000,
    20000000,
    30000000,
    50000000,
    75000000,
    100000000,
    250000000,
    500000000,
    1000000000,
    5000000000,
    10000000000,
    25000000000,
    50000000000,
    100000000000
] %}
{% block main %}
    <div class="row row-cards">
        <div class="col-12">
            <div class="alert alert-success" role="alert">
                Примерный ТОП игрков игры Храбрый Полк. Последнее обновление
                <b>{{ convertTime(update[0].updateTime) }}</b>.
            </div>
            <div class="card">
                <div class="table-responsive">
                    <table class="table card-table table-vcenter text-nowrap datatable">
                        <thead>
                        <tr>
                            <th class="w-1">№</th>
                            <th class="w-3">Имя Фамилия</th>
                            <th{% if pagination.isSorted(['a.experience']) %} class="sorted"{% endif %}>
                                {{ knp_pagination_sortable(pagination, 'Уровень', ['a.experience']) }}
                            </th>
                            <th{% if pagination.isSorted(['a.sut']) %} class="sorted"{% endif %}>
                                {{ knp_pagination_sortable(pagination, 'СУТ', ['a.sut']) }}
                            </th>
                            <th{% if pagination.isSorted(['a.used_talents']) %} class="sorted"{% endif %}>
                                {{ knp_pagination_sortable(pagination, 'Таланты', ['a.used_talents']) }}
                            </th>
                            <th{% if pagination.isSorted(['a.total_damage']) %} class="sorted"{% endif %}>
                                {{ knp_pagination_sortable(pagination, 'Урон', ['a.total_damage']) }}
                            </th>
                            <th{% if pagination.isSorted(['a.loginTime']) %} class="sorted"{% endif %}>
                                {{ knp_pagination_sortable(pagination, 'Вход в игру', ['a.login_time']) }}
                            </th>
                            <th>Статистика</th>
                            <th>
                                <div class="dropdown">
                                    <a class="dropdown-toggle text-muted" href="#" data-bs-toggle="dropdown"
                                       aria-haspopup="true" aria-expanded="false">
                                        Статус
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-end">

                                        {% if app.user %}
                                            <a class="dropdown-item"
                                               href="{{ path('top', app.request.query.all|merge({'friends': 'yes'})) }}">
                                                Друзья
                                            </a>
                                            <a class="dropdown-item"
                                               href="{{ path('top', app.request.query.all|merge({'friends': 'no'})) }}">
                                                Нет в друзьях
                                            </a>
                                        {% endif %}
                                        <a class="dropdown-item"
                                           href="{{ path('top', app.request.query.all|merge({'friends': 'all'})) }}">
                                            Весь список
                                        </a>
                                    </div>
                                </div>
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        {% if app.user %}
                            <tr data-id="{{ profile.user.id }}">
                                <td>
                                    {{ profile.top }}
                                </td>
                                <td>
                                    <div class="d-flex py-1 align-items-center">
                                        <a href="https://vk.com/id{{ profile.user.socId }}"
                                           class="text-reset" target="_blank"><span class="avatar me-2"
                                                                                    style="background-image: url({{ profile.user.photo50 }})"></span>
                                        </a>
                                        <div class="flex-fill">
                                            <div class="font-weight-medium">
                                                <a href="https://vk.com/id{{ profile.user.socId }}"
                                                   class="text-reset" target="_blank">
                                                    {{ profile.user.firstName }} {{ profile.user.lastName }}
                                                </a>
                                            </div>
                                            <div class="text-muted">
                                                <div class="text-reset">
                                                    @id{{ profile.user.socId }}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    {% if level[profile.user.level] is defined and level[profile.user.level] is not empty %}
                                        {% set levels = profile.user.experience - level[profile.user.level - 1] ?? 0 %}
                                        {% set procent =  levels * 100 / (level[profile.user.level] - level[ profile.user.level - 1]) %}
                                        <div class="text-muted"> {{ profile.user.level }} ({{ procent|round }}%)</div>
                                    {% else%}
                                        <div class="text-muted"> {{ profile.user.level }} (0%)</div>
                                    {% endif %}
                                </td>
                                <td>
                                    <div class="text-muted">{{ profile.user.sut }}</div>
                                </td>
                                <td>
                                    <div class="text-muted"> {{ profile.user.usedTalents }}</div>
                                </td>
                                <td>
                                    <div class="text-muted">  {{ damage[profile.user.totalDamage]|number_format(0, ',', '.') }}</div>
                                </td>
                                <td>
                                    <div class="text-muted"> {{ convertTime(profile.user.loginTime) }}</div>
                                </td>
                                <td>
                                    <div class="text-muted">

                                        <a href="{{ path('top-stats', {'id': profile.user.id }) }}"
                                           class="text-reset">
                                            просмотреть
                                        </a>
                                    </div>
                                </td>

                                <td>
                                    <span class="badge bg-success me-1"></span>ваша страница
                                </td>
                            </tr>
                        {% endif %}

                        {% for item in pagination %}
                            <tr data-id="{{ item.id }}">
                                <td>
                                    {{ (pagination.currentPageNumber-1) * 250 + loop.index }}
                                </td>
                                <td>
                                    <div class="d-flex py-1 align-items-center">
                                        <a href="https://vk.com/id{{ item.socId }}"
                                           class="text-reset" target="_blank"><span class="avatar me-2"
                                                                                    style="background-image: url({{ item.photo50 }})"></span>
                                        </a>
                                        <div class="flex-fill">
                                            <div class="font-weight-medium">
                                                <a href="https://vk.com/id{{ item.socId }}"
                                                   class="text-reset" target="_blank">
                                                    {{ item.firstName }} {{ item.lastName }}
                                                </a>
                                            </div>
                                            <div class="text-muted">
                                                <div class="text-reset">
                                                    @id{{ item.socId }}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    {% if level[item.level] is defined and level[item.level] is not empty %}
                                        {% set levels = item.experience - level[item.level - 1]  %}
                                        {% set procent =  levels * 100 / (level[item.level] - level[item.level - 1]) %}
                                        <div class="text-muted"> {{ item.level }} ({{ procent|round }}%)</div>
                                    {% else%}
                                           <div class="text-muted"> {{ item.level }} (0%)</div>
                                    {% endif %}
                                </td>
                                <td>
                                    <div class="text-muted">{{ item.sut }}</div>
                                </td>
                                <td>
                                    <div class="text-muted"> {{ item.usedTalents }}</div>
                                </td>
                                <td>
                                    <div class="text-muted">  {{ damage[item.totalDamage]|number_format(0, ',', '.') }}</div>
                                </td>
                                <td>
                                    <div class="text-muted"> {{ convertTime(item.loginTime) }}</div>
                                </td>
                                <td>
                                    <div class="text-muted">

                                        <a href="{{ path('top-stats', {'id': item.id }) }}"
                                           class="text-reset">
                                            просмотреть
                                        </a>
                                    </div>
                                </td>
                                <td>
                                    {% if app.user %}
                                        {% if array_search(item.socId, friends) %}
                                            <span class="badge bg-success me-1"></span>есть в друзьях
                                        {% else %}
                                            <span class="badge bg-danger me-1"></span>не добавлен
                                        {% endif %}
                                    {% else %}
                                        <span class="badge bg-success me-1"></span> не известно
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                {{ knp_pagination_render(pagination, 'libs/pagination.html.twig') }}
            </div>
        </div>
    </div>
{% endblock %}