src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Integer;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string')]
    private int $vkontakteID;

    #[ORM\Column(type: 'integer')]
    private $updateTime;

    #[ORM\Column(type: 'string', length: 255)]
    private $access_token;

    #[ORM\Column(type: 'string', length: 255)]
    private $first_name;

    #[ORM\Column(type: 'string', length: 255)]
    private $last_name;

    #[ORM\Column(type: 'string', length: 255)]
    private $screen_name;

    #[ORM\Column(type: 'string', length: 255)]
    private $photo_medium;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Ads::class)]
    private $ads;

    #[ORM\OneToOne(mappedBy: 'user', targetEntity: UsersToken::class, cascade: ['persist', 'remove'])]
    private $usersToken;

    public function __construct()
    {
        $this->ads = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return int
     */
    public function getVkontakteID(): int
    {
        return $this->vkontakteID;
    }

    /**
     * @param mixed $vkontakteID
     */
    public function setVkontakteID(int $vkontakteID): self
    {
        $this->vkontakteID = $vkontakteID;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }


    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getUpdateTime(): ?int
    {
        return $this->updateTime;
    }

    public function setUpdateTime(int $updateTime): self
    {
        $this->updateTime = $updateTime;

        return $this;
    }

    public function getAccessToken(): ?string
    {
        return $this->access_token;
    }

    public function setAccessToken(string $access_token): self
    {
        $this->access_token = $access_token;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getScreenName(): ?string
    {
        return $this->screen_name;
    }

    public function setScreenName(string $screen_name): self
    {
        $this->screen_name = $screen_name;

        return $this;
    }

    public function getPhotoMedium(): ?string
    {
        return $this->photo_medium;
    }

    public function setPhotoMedium(string $photo_medium): self
    {
        $this->photo_medium = $photo_medium;

        return $this;
    }

    /**
     * @return Collection|Ads[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ads $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setUser($this);
        }

        return $this;
    }

    public function removeAd(Ads $ad): self
    {
        if ($this->ads->removeElement($ad)) {
            // set the owning side to null (unless already changed)
            if ($ad->getUser() === $this) {
                $ad->setUser(null);
            }
        }

        return $this;
    }

    public function getUsersToken(): ?UsersToken
    {
        return $this->usersToken;
    }

    public function setUsersToken(?UsersToken $usersToken): self
    {
        // unset the owning side of the relation if necessary
        if ($usersToken === null && $this->usersToken !== null) {
            $this->usersToken->setUser(null);
        }

        // set the owning side of the relation if necessary
        if ($usersToken !== null && $usersToken->getUser() !== $this) {
            $usersToken->setUser($this);
        }

        $this->usersToken = $usersToken;

        return $this;
    }
}

src/Controller/ScannerController.php
<?php

namespace App\Controller;

use App\Repository\UsersTokenRepository;
use App\Service\Scanner;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ScannerController extends AbstractController
{
    #[Route('/scanner/authorized', name: 'scanner-authorized')]
    public function index(UsersTokenRepository $usersTokenRepository): Response
    {
        if ($usersTokenRepository->findOneBy(['user' => $this->getUser()])) {
            return $this->redirectToRoute('scanner-friends');
        }
        return $this->render('scanner/authorized.html.twig');
    }

    #[Route('/scanner/friends', name: 'scanner-friends')]
    public function friends(UsersTokenRepository $usersTokenRepository): Response
    {
        $user = $usersTokenRepository->findOneBy(['user' => $this->getUser()]);

        if (isset($user)) {
            return $this->render('scanner/friends.html.twig', [
                'user' => $user
            ]);
        }
        return $this->redirectToRoute('scanner-authorized');
    }

    #[Route('/scanner/api/setToken', name: 'scanner-set-token')]
    public function addToken(Request $request, Scanner $scanner): Response
    {
        if ($token = $request->get('access_token')) {
            return $this->json($scanner->addedToken($token));
        }
        return $this->json(['status' => 0, 'error' => ['messages' => 'Ошибка!']]);
    }

    #[Route('/scanner/api/getUsers', name: 'scanner-users')]
    public function getUsers(Request $request, Scanner $scanner): Response
    {
        if ($users_uid = $request->get('users_ids')) {
            return $this->json($scanner->getUsers($users_uid));
        }
        return $this->json(['status' => 0, 'error' => ['messages' => 'Ошибка!']]);
    }
}

templates/scanner/authorized.html.twig
{% extends 'base.html.twig' %}
{% block title 'Сканер друзей' %}
{% block header 'Сканер друзей' %}
{% block main %}
    <div class="row row-cards">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Авторизация</h3>
                </div>
                <div class="card-body p-4">
                    <div class="bg-light p-3">Нажмите на эту кнопку&nbsp;&nbsp;<a
                                href="https://oauth.vk.com/authorize?client_id=2685278&scope=friends,offline,apps&redirect_uri=https://oauth.vk.com/blank.html&display=page&response_type=token"
                                target="_blank" class="btn btn-primary">Получить access_token</a></div>

                    <div class="accordion" style="margin: 20px 0;">
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="heading-2">
                                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                        data-bs-target="#collapse-2" aria-expanded="false">
                                    Если появилось окно с запросом доступа, нажмите кнопку "Разрешить"
                                </button>
                            </h2>
                            <div id="collapse-2" class="accordion-collapse collapse"
                                 data-bs-parent="#accordion-example">
                                <div class="accordion-body pt-0">
                                    <img src="{{ asset('build/static/AppStartToken.png') }}" width="100%"
                                         alt="{{ asset('build/static/AppStartToken.png') }}">
                                </div>
                            </div>
                        </div>
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="heading-3">
                                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                        data-bs-target="#collapse-3" aria-expanded="false">
                                    Скопируйте содержимое адресной строки.
                                </button>
                            </h2>
                            <div id="collapse-3" class="accordion-collapse collapse"
                                 data-bs-parent="#accordion-example">
                                <div class="accordion-body pt-0">
                                    <img src="{{ asset('build/static/accessEnd.png') }}" width="100%"
                                         alt="{{ asset('build/static/accessEnd.png') }}"></div>
                            </div>
                        </div>
                    </div>
                    <div class="bg-light p-3">
                        <div id="alert"></div>
                        <form id="addToken">
                            <div class="input-group mb-2">
                                <input type="text" placeholder="Вставьте содержимое адресной строки."
                                       pattern=".*[0-9a-f]{85,93}.*" class="form-control" name="access_token">
                                <button class="btn" type="submit">Добавить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/scanner/friends.html.twig
{% extends 'base.html.twig' %}
{% block title 'Сканер друзей' %}
{% block header 'Сканер друзей' %}
{% block main %}
    <script>
        window.access_token = '{{ user.accessToken }}';
    </script>
    <div class="row row-deck row-cards">
        <div class="col-md-4 col-lg-4">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Сканер ваших друзей</h3>
                </div>
                <div class="card-body">
                    <div id="alert"></div>
                    <form id="scannerForm">
                        <div class="form-footer">
                            <div class="row justify-content-center">
                                <div class="col-lg-4">
                                    <button type="submit" name="friends_bot" class="btn btn-primary">Сканер друзей</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-8 col-lg-8">
            <div class="card" style="height: calc(37rem + 10px)">
                <div class="card-header">
                    <h3 class="card-title">Список аккаунтов</h3>
                </div>
                <div class="card-body card-body-scrollable card-body-scrollable-shadow">
                    <div class="table-responsive">
                        <table class="table table-hover" id="ads-table">
                            <thead>
                            <tr>
                                <th>№</th>
                                <th>Имя Фамилия</th>
                                <th>Уровень</th>
                                <th>СУТ</th>
                                <th>Таланты</th>
                                <th>Урон</th>
                                <th>Вход в игру</th>
                                <th>Статистика</th>
                            </tr>
                            </thead>
                            <tbody id="usersTable">

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}