src/Entity/Ads.php
<?php

namespace App\Entity;

use App\Repository\AdsRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: AdsRepository::class)]
class Ads
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'ads')]
    #[ORM\JoinColumn(nullable: false)]
    private $user;

    #[ORM\Column(type: 'text', length: 100)]
    #[
        Assert\NotBlank(message: 'Введите сообщение'),
        Assert\Length(
            min: 10,
            max: 100
        )
    ]
    private $messages;

    #[ORM\Column(type: 'integer')]
    private $created;

    #[ORM\Column(type: 'string', length: 255)]

    #[Assert\Regex(
        pattern: "#^https?\:\/\/(?:www\.)?vk.com\/#",
        message: "Ссылка должна вести на Вконтакте."
    )]
    private $redirect;

    #[ORM\Column(type: 'integer')]
    private $count = 0;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $last_time = 0;

    #[ORM\Column(type: 'string', length: 255)]
    private $type;

    #[ORM\Column(type: 'integer')]
    private $views = 0;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    public function __construct(){
        $this->created = time();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser( $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getMessages(): ?string
    {
        return $this->messages;
    }

    public function setMessages(string $messages): self
    {
        $this->messages = $messages;

        return $this;
    }

    public function getCreated(): ?int
    {
        return $this->created;
    }

    public function setCreated(int $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getRedirect(): ?string
    {
        return $this->redirect;
    }

    public function setRedirect(string $redirect): self
    {
        $this->redirect = $redirect;

        return $this;
    }

    public function getCount(): ?int
    {
        return $this->count;
    }

    public function setCount(int $count): self
    {
        $this->count = $count;

        return $this;
    }

    public function getLastTime(): ?int
    {
        return $this->last_time;
    }

    public function setLastTime(?int $last_time): self
    {
        $this->last_time = $last_time;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getViews(): ?int
    {
        return $this->views;
    }

    public function setViews(int $views): self
    {
        $this->views = $views;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
}

src/Form/AdsType.php
<?php

namespace App\Form;

use App\Entity\Ads;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('messages', TextareaType::class, [
                'label' => 'Сообщение',
                'attr' => [
                    'rows' => 10,
                    'maxlength' => 100,
                    'placeholder' => 'Введите сообщение',
                ],
                'required' => false,
            ])
            ->add('redirect', TextType::class, [
                'label' => 'Ссылка на страницу',
                'attr' => [
                    'placeholder' => 'Введите ссылку на страницу',
                ],
                'required' => false,
            ])
            ->add('name', TextType::class, [
                'label' => 'Имя',
                'attr' => [
                    'placeholder' => 'Введите имя для пиара',
                ],
                'required' => false,
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'Добавить',
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Ads::class,
        ]);
    }
}

src/Controller/AdsController.php
<?php

namespace App\Controller;

use App\Entity\Ads;
use App\Form\AdsType;
use App\Repository\AdsRepository;
use App\Service\AdsService;
use App\Service\FormError;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AdsController extends AbstractController
{
    #[Route('/ads', name: 'ads')]
    #[IsGranted('IS_AUTHENTICATED_FULLY')]
    public function index(Request $request, FormError $formError, AdsService $adsService, AdsRepository $adsRepository): Response
    {
        $ads = new Ads();
        $ads->setUser($this->getUser());

        $form = $this->createForm(AdsType::class, $ads);
        $form->handleRequest($request);

        if ($request->isXmlHttpRequest()) {
            if ($form->isSubmitted() && $form->isValid()) {
                return $this->json($adsService->create($ads));
            }
            return $this->json(['status' => 0, 'error' => ['messages' => $formError->getErrorMessages($form)]]);
        }

        return $this->render('ads/index.html.twig', [
            'form' => $form->createView(),
            'items' => $adsRepository->findBy(['user' => $this->getUser()], ['id' => 'DESC']),
            'type' => AdsService::TYPE
        ]);
    }

    #[
        Route('/ads/remove', name: 'ads-remove', methods: ['POST'])
    ]
    #[IsGranted('IS_AUTHENTICATED_FULLY')]
    public function remove(Request $request, AdsRepository $adsRepository, AdsService $adsService): Response
    {
        if ($ads = $adsRepository->findOneBy(['id' => (int)$request->get('id', 0), 'user' => $this->getUser()])) {
            return $this->json($adsService->remove($ads));
        }
        return $this->json(['status' => 0, 'error' => ['messages' => 'Аккаунт не найден!']]);
    }

    #[
        Route('/ads/views/{id}', name: 'ads-views', methods: ['GET'])
    ]
    public function views(Request $request, AdsRepository $adsRepository, int $id, EntityManagerInterface $entityManager): Response
    {
        if ($ads = $adsRepository->findOneBy(['id' => (int)$id])) {
            $ads->setLastTime(time())
                ->setCount($ads->getCount() + 1);

            $entityManager->flush();

            return $this->redirect(AdsService::TYPE[$ads->getType()]['url'] . $ads->getRedirect());
        }
        return $this->redirectToRoute('top');
    }
}

templates/ads/ads.item.html.twig
<tr id="ads_{{ ads.id }}" data-ads-id="{{ ads.id }}">
    <td>{{ ads.id }}</td>
    <td>{{ type[ads.type]['name'] }}</td>
    <td><a href="{{ type[ads.type]['url'] }}{{ ads.redirect }}"
           target="_blank">{{ ads.name }}</a></td>
    <td>{{ convertTime(ads.created) }}</td>
    <td>{{ ads.views }} {{ rename(['раз', 'раза', 'раз'], ads.views) }}</td>
    {% if ads.lastTime > 0 %}
        <td>{{ convertTime(ads.redirect) }}</td>
    {% else %}
        <td>нет переходов</td>
    {% endif %}
    <td>{{ ads.count }} {{ rename(['раз', 'раза', 'раз'], ads.count) }}</td>
    <td>
                                    <span class="text-muted cursor-pointer" data-bs-toggle="tooltip"
                                          data-bs-placement="bottom" data-bs-original-title="Удалить"
                                          id="delete-ads">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24"
                                                 viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                                                 stroke-linecap="round" stroke-linejoin="round"><path stroke="none"
                                                                                                      d="M0 0h24v24H0z"
                                                                                                      fill="none"></path><line
                                                        x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18"
                                                                                                   y2="18"></line></svg> </span>
    </td>
</tr>

templates/ads/index.html.twig
{% extends 'base.html.twig' %}
{% block title 'Реклама' %}
{% block header 'Реклама в скрипте' %}
{% block main %}
    <div class="row row-deck row-cards">
        <div class="col-md-4 col-lg-4">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Добавление объявления</h3>
                </div>
                <div class="card-body">
                    <div id="alert"></div>
                    {{ form_start(form, {'action': path('ads'), 'attr': {'id': 'adsForm'}}) }}
                    <div class="mb-3">
                        <label class="form-label">{{ form_label(form.redirect) }}</label>
                        {{ form_row(form.redirect) }}
                    </div>
                    <div class="mb-3">
                        <label class="form-label">{{ form_label(form.name) }}</label>
                        {{ form_row(form.name) }}
                    </div>
                    <div class="mb-3">
                        <label class="form-label">{{ form_label(form.messages) }}</label>
                        {{ form_row(form.messages) }}
                        <small class="form-hint">
                            Сообщение типа, 100ккк урона, 5000 сут.
                        </small>
                    </div>
                    <div class="form-footer ">
                        {{ form_widget(form.submit, {'attr': {'class': 'btn btn-primary'}}) }}
                    </div>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
        <div class="col-md-8 col-lg-8">
            <div class="card" style="height: calc(37rem + 10px)">
                <div class="card-header">
                    <h3 class="card-title">Список аккаунтов</h3>
                </div>
                <div class="card-body card-body-scrollable card-body-scrollable-shadow">
                    <div class="table-responsive">
                        <table class="table table-hover" id="ads-table">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Категория</th>
                                <th>Источник</th>
                                <th>Создан</th>
                                <th>Показов</th>
                                <th>Последний переход</th>
                                <th>Переходов</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody id="adsTable">
                            {% for item in items %}
                                <tr id="ads_{{ item.id }}" data-ads-id="{{ item.id }}">
                                    <td>{{ item.id }}</td>
                                    <td>{{ type[item.type]['name'] }}</td>
                                    <td><a href="{{ type[item.type]['url'] }}{{ item.redirect }}"
                                           target="_blank">{{ item.name }}</a></td>
                                    <td>{{ convertTime(item.created) }}</td>
                                    <td>{{ item.views }} {{ rename(['раз', 'раза', 'раз'], item.views) }}</td>
                                    {% if item.lastTime > 0 %}
                                        <td>{{ convertTime(item.lastTime) }}</td>
                                    {% else %}
                                        <td>нет переходов</td>
                                    {% endif %}
                                    <td>{{ item.count }} {{ rename(['раз', 'раза', 'раз'], item.count) }}</td>
                                    <td>
                                        <span class="text-muted cursor-pointer" data-bs-toggle="tooltip"
                                              data-bs-placement="bottom" data-bs-original-title="Удалить"
                                              id="delete-ads">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24"
                                                 viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                                                 stroke-linecap="round" stroke-linejoin="round"><path stroke="none"
                                                                                                      d="M0 0h24v24H0z"
                                                                                                      fill="none"></path><line
                                                        x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18"
                                                                                                   y2="18"></line>
                                            </svg>
                                        </span>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}